import React, { useState } from 'react';
import { Copy, Download, Check } from 'lucide-react';
import type { Interruption } from '../../types';

const colors = {
  primary: '#6366F1',
  primaryLight: '#818CF8',
  bgPrimary: '#0F172A',
  bgSecondary: '#1E293B',
  bgCard: '#334155',
  textPrimary: '#F8FAFC',
  textSecondary: '#94A3B8',
  border: '#475569',
  positive: '#10B981',
};

function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins}m ${secs}s`;
}

function formatTimestamp(date: Date): string {
  const d = date instanceof Date ? date : new Date(date);
  const hours = String(d.getHours()).padStart(2, '0');
  const mins = String(d.getMinutes()).padStart(2, '0');
  const secs = String(d.getSeconds()).padStart(2, '0');
  return `${hours}:${mins}:${secs}`;
}

function buildExportText(
  interruptions: Interruption[],
  platform: string,
  duration: number,
): string {
  const platformName = platform.charAt(0).toUpperCase() + platform.slice(1);
  const lines: string[] = [];

  lines.push('========================================');
  lines.push('  Creator Copilot - Session Notes');
  lines.push('========================================');
  lines.push('');
  lines.push(`Platform: ${platformName}`);
  lines.push(`Duration: ${formatDuration(duration)}`);
  lines.push(`Date: ${new Date().toLocaleDateString()}`);
  lines.push(`Total Feedback: ${interruptions.length}`);
  lines.push('');
  lines.push('----------------------------------------');
  lines.push('  FEEDBACK LOG');
  lines.push('----------------------------------------');
  lines.push('');

  if (interruptions.length === 0) {
    lines.push('No feedback was provided during this session.');
  } else {
    interruptions.forEach((item, index) => {
      const typeLabel = item.type.charAt(0).toUpperCase() + item.type.slice(1);
      const responseLabel =
        item.userResponse === 'acknowledged' || item.userResponse === 'expanded'
          ? 'FIXED'
          : 'NOTED';

      lines.push(`${index + 1}. [${typeLabel}] [${responseLabel}]`);
      lines.push(`   Time: ${formatTimestamp(item.timestamp)}`);
      if (item.issue) {
        lines.push(`   Issue: ${item.issue}`);
      }
      lines.push(`   Advice: ${item.advice}`);
      if (item.example) {
        lines.push(`   Example: ${item.example}`);
      }
      lines.push('');
    });
  }

  lines.push('----------------------------------------');
  lines.push('  Generated by Creator Copilot');
  lines.push('----------------------------------------');

  return lines.join('\n');
}

interface FeedbackExportProps {
  interruptions: Interruption[];
  platform: string;
  duration: number;
}

export default function FeedbackExport({
  interruptions,
  platform,
  duration,
}: FeedbackExportProps) {
  const [copied, setCopied] = useState(false);
  const [hoveredButton, setHoveredButton] = useState<string | null>(null);

  const handleCopy = async () => {
    const text = buildExportText(interruptions, platform, duration);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
  };

  const handleDownload = () => {
    const text = buildExportText(interruptions, platform, duration);
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    const dateStr = new Date().toISOString().split('T')[0];
    link.href = url;
    link.download = `creator-copilot-notes-${platform}-${dateStr}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div
      style={{
        padding: '18px 20px',
        borderRadius: 12,
        background: colors.bgSecondary,
        border: `1px solid ${colors.border}`,
        display: 'flex',
        flexDirection: 'column',
        gap: 14,
      }}
    >
      <div>
        <h3
          style={{
            fontSize: 14,
            fontWeight: 600,
            color: colors.textPrimary,
            margin: '0 0 4px 0',
          }}
        >
          Export Session Notes
        </h3>
        <p
          style={{
            fontSize: 13,
            color: colors.textSecondary,
            margin: 0,
            lineHeight: 1.4,
          }}
        >
          Save your feedback log as text for future reference.
        </p>
      </div>

      <div
        style={{
          display: 'flex',
          gap: 10,
        }}
      >
        <button
          onClick={handleCopy}
          onMouseEnter={() => setHoveredButton('copy')}
          onMouseLeave={() => setHoveredButton(null)}
          style={{
            flex: 1,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            padding: '12px 16px',
            borderRadius: 10,
            border: `1.5px solid ${copied ? colors.positive : colors.border}`,
            background: copied
              ? `${colors.positive}15`
              : hoveredButton === 'copy'
                ? colors.bgCard
                : 'transparent',
            color: copied ? colors.positive : colors.textPrimary,
            fontSize: 13,
            fontWeight: 600,
            cursor: 'pointer',
            transition: 'all 0.2s ease',
            fontFamily: 'inherit',
          }}
        >
          {copied ? <Check size={16} /> : <Copy size={16} />}
          {copied ? 'Copied!' : 'Copy to Clipboard'}
        </button>

        <button
          onClick={handleDownload}
          onMouseEnter={() => setHoveredButton('download')}
          onMouseLeave={() => setHoveredButton(null)}
          style={{
            flex: 1,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            padding: '12px 16px',
            borderRadius: 10,
            border: 'none',
            background:
              hoveredButton === 'download' ? colors.primaryLight : colors.primary,
            color: '#fff',
            fontSize: 13,
            fontWeight: 600,
            cursor: 'pointer',
            transition: 'all 0.2s ease',
            fontFamily: 'inherit',
          }}
        >
          <Download size={16} />
          Download
        </button>
      </div>
    </div>
  );
}
